"""test

Revision ID: 898affe2a9f5
Revises: 
Create Date: 2023-06-13 19:35:38.084457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898affe2a9f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.String(), server_default='', nullable=False),
    sa.Column('textfield', sa.Text(), server_default='', nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
