version: "3"

services:
  pg:
    container_name: "pg-db"
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"